### ISSUE TITLE
Spanish Support

### ISSUE THREAD

**Issue by EhuddR** [anufrievroman/Angry-Reviewer#1]
Hello, this tool is very useful but it could be more powerful if it had support for other languages, is there a possibility that other languages could be supported in the future?

**Comment by anufrievroman** [comment]
Hi, thank you! Well, adding support to other languages means that someone needs to rewrite the whole database of rules, which is the core of this program. Even adding support for my native language (Russian) seems like an impossible task at the moment, because I don't have that much experience with Russian academic writing, and I don't know if there is any literature on the matter. So, adding support for other languages essentially means that someone needs to fork the project and work hard to recreate rules.py file for the new language...

**Comment by EhuddR** [comment]
I see. Sadly I don't know python. Thank you anyway!
